config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :usuario do
    get "sign_out" => "devise/sessions#destroy"
    get "salir" => "devise/sessions#destroy",
      as: :terminar_sesion

    post "usuarios/iniciar_sesion", to: "devise/sessions#create"
    get "usuarios/iniciar_sesion",
      to: "devise/sessions#new",
      as: :iniciar_sesion

    # El siguiente para superar mala generación del action en el formulario
    # cuando se monta en sitio diferente a / y se autentica mal (genera
    # /puntomontaje/puntomontaje/usuarios/sign_in )
    if Rails.configuration.relative_url_root != "/"
      ruta = File.join(
        Rails.configuration.relative_url_root,
        "usuarios/sign_in",
      )
      post ruta, to: "devise/sessions#create"
      get  ruta, to: "devise/sessions#new"
    end
  end

  devise_for :usuarios, skip: [:registrations], module: :devise
  as :usuario do
    get "usuarios/edit" => "devise/registrations#edit",
      :as => "editar_registro_usuario"
    put "usuarios/:id" => "devise/registrations#update",
      :as => "registro_usuario"
  end
  resources :usuarios, path_names: { new: "nuevo", edit: "edita" }

  get "proyectofinanciero/:id/actualizar_de_gitlab" =>
  "cor1440_gen/proyectosfinancieros#actualizar_de_gitlab",
    as: "actualizar_de_gitlab"

  resources(
    :informesavanzados,
    controller: "heb412_gen/informesavanzados",
    path_names: { new: "nuevo", edit: "edita" },
  ) do
    resources(
      :bloquesinfav,
      controller: "heb412_gen/bloquesinfav",
      path_names: { new: "nuevo", edit: "edita" },
    ) do
      member do
        patch :mover
      end
    end
  end

  root "msip/hogar#index"
  mount Msip::Engine, at: "/", as: "msip"
  mount Heb412Gen::Engine, at: "/", as: "heb412_gen"
  mount Mr519Gen::Engine, at: "/", as: "mr519_gen"
  mount Cor1440Gen::Engine, at: "/", as: "cor1440_gen"
end

app/views/layouts/application.html.erb
<% content_for :title do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus_prosidebar do %>
    <% if can? :read, Cor1440Gen::Actividad %>
      <%= despliega_abajo_prosidebar "Actividades", 'ri-riding-fill', nil do %>
        <%= opcion_menu_prosidebar "Listado", cor1440_gen.actividades_path, 
          desplegable: true %>
        <% if can? :read, Cor1440Gen::Informe %>
          <%= opcion_menu_prosidebar "Informes", cor1440_gen.informes_path,
            desplegable: true %>
        <% end %>
        <% if can? :read, Msip::Persona %>
          <%= opcion_menu_prosidebar "Persona", msip.personas_path,
            desplegable: true %>
        <% end %>
        <% if can? :read, Msip::Orgsocial %>
          <%= opcion_menu_prosidebar "Organizaciones sociales", msip.orgsociales_path,
            desplegable: true %>
        <% end %>
      <% end %>
    <% end %>
    <% if can? :read, Cor1440Gen::Proyectofinanciero %>
      <%= opcion_menu_prosidebar "Convenios", 
        cor1440_gen.proyectosfinancieros_path, icono: 'ri-briefcase-4-fill' %>
    <% end %>
    <% if can? :index, Cor1440Gen::Efecto %>
      <%= despliega_abajo_prosidebar "Indicadores", 
        'ri-line-chart-fill', nil do %>
        <%= opcion_menu_prosidebar "Medición", 
          cor1440_gen.mindicadorespf_path, desplegable: true %>
        <%= opcion_menu_prosidebar "Avance en indicadores de Efecto", 
          cor1440_gen.efectos_path, desplegable: true %>
      <% end %>
    <% end %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo_prosidebar "Documentos y plantillas", 
        'ri-book-open-fill', nil do %>
        <%= opcion_menu_prosidebar "Nube", heb412_gen.sisini_path,
          desplegable: true %>
        <% if can? :manage, ::Heb412Gen::Plantillahcm %>
          <%= opcion_menu_prosidebar "Plantillas para listados en hojas de calculo",
            heb412_gen.plantillashcm_path,
          desplegable: true %>
        <% end %>
        <% if can? :manage, ::Heb412Gen::Plantillahcr %>
          <%= opcion_menu_prosidebar "Plantillas para un registro en hoja de calculo",
            heb412_gen.plantillashcr_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo_prosidebar "Administrar", 
        'ri-settings-4-fill', nil do %>
        <%= opcion_menu_prosidebar "Clave y tema", main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu_prosidebar "Usuarios", main_app.usuarios_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu_prosidebar "Formularios", mr519_gen.formularios_path,
            desplegable: true %>
        <% end %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu_prosidebar "Tablas Básicas", msip.tablasbasicas_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= opcion_menu_prosidebar "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu_prosidebar "Acerca de", msip.acercade_path %>
      <%= opcion_menu_prosidebar "Iniciar Sesión", 
        main_app.iniciar_sesion_path %> 
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p><span class='derechos'>Sistema de información de 
    <a href='https://github.com/pasosdeJesus/cor1440_pdJ'>código abierto</a> 
    con <a href="https://github.com/pasosdeJesus/msip/blob/main/LICENCIA.md">licencia ISC</a>
    <br/>
    Desarrollado por <a id='pasosdeJesus' href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. <%= Date.today.year %>. 
<% end %>

<%= render template: "layouts/msip/application-prosidebar" %>